name: 'Github Clone Workflow'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.MY_NETLIFY_TOKEN_SECRET }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
